dist: xenial
language: python
cache: pip

# Drop once EOL: https://devguide.python.org/#status-of-python-branches
python:
  - '2.7'
  - '3.5'
  - '3.6'

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew install python3
    python3 --version
  fi
install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    pip3 install tox
  else
    pip install tox
  fi
script:
  - 'tox'

matrix:
  include:
    # "coverage" toxenv runs tests, so no need to run TOXENV=py37
    - python: '3.7'
      env: TOXENV=black,pylint,pytype,bandit,coverage

    # OSX -- takes a while to start up on Travis, so once we get a worker just
    # run them all with one instance of tox
    - os: osx
      language: generic
      env: TOXENV=py27,py35,py36,py37
