language: python
cache: pip

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install python3
    python3 --version
  fi

install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    pip3 install tox
  else
    pip install tox
  fi

script:
  - 'tox'

matrix:
  fast_finish: true
  include:
    # One-off runs
    - python: '3.6'
      env: TOXENV=coverage
    - python: '3.5'  # 3.6 after https://github.com/PyCQA/pylint/issues/1113
      env: TOXENV=pylint

    # OSX -- takes a while to start up on Travis, so once we get a worker just
    # run them all with one instance of tox
    - os: osx
      language: generic
      env: TOXENV=py36

# This is required to enable container based Travis CI infrastructure.
# See http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
